# Generated by Django 3.1.5 on 2021-01-20 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchProteins',
            fields=[
                ('dnasequence', models.TextField(primary_key=True, verbose_name='DNA Sequence')),
                ('status', models.TextField(default="Running", verbose_name='Status')),
                ('match', models.TextField(default="None", verbose_name='Match')),
            ],
        ),
    ]
